#!/system/bin/sh
# L SPEED MOD
# Copyright (C) 2015 Paget96
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

busybox mount -o remount,rw /
busybox mount -o remount,rw rootfs
busybox mount -o remount,rw /system

LS=/system/etc/L_SPEED/00L_STUFF/LOGS/LS_IO.log

busybox rm -f $LS
busybox touch $LS

busybox echo "# L Speed log" | tee -a $LS
busybox echo "" | tee -a $LS
busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ) Adding I/O speed tweak..." | tee -a $LS

path=`busybox ls -d /sys/block/* 2>/dev/null`;
for S in $path;
do
	if [ -e $S/queue/rotational ]; then
		busybox echo "0" > $S/queue/rotational
	fi
	if [ -e $S/queue/iostats ]; then
		busybox echo "0" > $S/queue/iostats
	fi
	if [ -e $S/queue/nr_requests ]; then
		busybox echo "1024" > $S/queue/nr_requests
	fi
	if [ -e $S/queue/nomerges ]; then
		busybox echo "0" > $S/queue/nomerges
	fi
  if [ -e $i/queue/iosched/fifo_batch ]; then
    busybox echo "1" > $i/queue/iosched/fifo_batch
  fi
  if [ -e $i/queue/iosched/writes_starved ]; then
    busybox echo "1" > $i/queue/iosched/writes_starved
   fi
done

busybox echo "Queue parameters are changed" | tee -a $LS

for L in $(busybox mount | grep relatime | cut -d " " -f3);
do
busybox mount -o noatime,remount $L
done

busybox echo "Realtime partitions are remounted" | tee -a $LS

for M in $(busybox mount | grep ext4 | cut -d " " -f3);
do
busybox mount -o noatime,remount,rw,discard,barrier=0,commit=60,noauto_da_alloc,delalloc $M
done

busybox echo "EXT4 partitions are remounted" | tee -a $LS

busybox echo "" | tee -a $LS
busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ) I/O speed tweak added" | tee -a $LS
