#!/system/bin/sh
# L SPEED MOD
# Copyright (C) 2015 Paget96
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

busybox mount -o remount,rw /
busybox mount -o remount,rw rootfs
busybox mount -o remount,rw /system

LS=/system/etc/L_SPEED/00L_STUFF/LOGS/LS_better_scrolling.log

busybox rm -f $LS
busybox touch $LS

busybox echo "# L Speed log" | tee -a $LS
busybox echo "" | tee -a $LS
busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ) Enabling better scolling.." | tee -a $LS

# Scrolling cache
setprop persist.sys.scrollingcache 3

busybox echo "Scrolling cache disabled.." | tee -a $LS

setprop windowsmgr.max_events_per_sec 90
setprop ro.max.fling_velocity 12000
setprop ro.min.fling_velocity 8000
setprop touch.deviceType touchScreen
setprop touch.orientationAware 1
setprop touch.size.calibration diameter
setprop touch.size.scale 32.0368
setprop touch.size.bias -5.1253
setprop touch.size.isSummed 0
setprop touch.pressure.calibration amplitude
setprop touch.pressure.scale 0.0125
setprop touch.orientation.calibration none

busybox echo "Other parameters tweaked.." | tee -a $LS

busybox echo "" | tee -a $LS
busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ) Better scrolling is enabled" | tee -a $LS
