#!/system/bin/sh
# L SPEED MOD
# Copyright (C) 2015 Paget96
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

busybox mount -o remount,rw /
busybox mount -o remount,rw rootfs
busybox mount -o remount,rw /system

LS=/system/etc/L_SPEED/00L_STUFF/LOGS/LS_ram_manager.log

busybox rm -f $LS
busybox touch $LS

busybox echo "# L Speed log " | tee -a $LS
busybox echo "" | tee -a $LS
busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ) Tweaking minfree values & adj lowmem values..." | tee -a $LS

# Cost
if [ -e /sys/module/lowmemorykiller/parameters/cost ]; then
    busybox chmod 644 /sys/module/lowmemorykiller/parameters/cost
    busybox echo "32" > /sys/module/lowmemorykiller/parameters/cost
  fi

# Debug level
if [ -e /sys/module/lowmemorykiller/parameters/debug_level ]; then
    busybox chmod 644 /sys/module/lowmemorykiller/parameters/debug_level
    busybox echo "0" > /sys/module/lowmemorykiller/parameters/debug_level
  fi

# ADJ Values
if [ -e /sys/module/lowmemorykiller/parameters/adj ]; then
    busybox chmod 644 /sys/module/lowmemorykiller/parameters/adj
    busybox echo "0,1,3,5,7,15" > /sys/module/lowmemorykiller/parameters/adj
   fi

# Minfree Values 
mem=`awk '/MemTotal/{print $2}' /proc/meminfo`

#512 and less
oom11=12
oom21=24
oom31=36
oom41=56
oom51=80
oom61=100

lmk11=$(($oom11*1024/4));
lmk21=$(($oom21*1024/4));
lmk31=$(($oom31*1024/4));
lmk41=$(($oom41*1024/4));
lmk51=$(($oom51*1024/4));
lmk61=$(($oom61*1024/4));

#768
oom12=24
oom22=40
oom32=48
oom42=64
oom52=80
oom62=100

lmk12=$(($oom12*1024/4));
lmk22=$(($oom22*1024/4));
lmk32=$(($oom32*1024/4));
lmk42=$(($oom42*1024/4));
lmk52=$(($oom52*1024/4));
lmk62=$(($oom62*1024/4));

#1024
oom13=26
oom23=42
oom33=50
oom43=66
oom53=82
oom63=100

lmk13=$(($oom13*1024/4));
lmk23=$(($oom23*1024/4));
lmk33=$(($oom33*1024/4));
lmk43=$(($oom43*1024/4));
lmk53=$(($oom53*1024/4));
lmk63=$(($oom63*1024/4));

#1536
oom14=32
oom24=48
oom34=56
oom44=68
oom54=86
oom64=106

lmk14=$(($oom14*1024/4));
lmk24=$(($oom24*1024/4));
lmk34=$(($oom34*1024/4));
lmk44=$(($oom44*1024/4));
lmk54=$(($oom54*1024/4));
lmk64=$(($oom64*1024/4));

#2048
oom15=48
oom25=60
oom35=72
oom45=84
oom55=96
oom65=120

lmk15=$(($oom15*1024/4));
lmk25=$(($oom25*1024/4));
lmk35=$(($oom35*1024/4));
lmk45=$(($oom45*1024/4));
lmk55=$(($oom55*1024/4));
lmk65=$(($oom65*1024/4));

#3072
oom16=64
oom26=80
oom36=96
oom46=112
oom56=128
oom66=144

lmk16=$(($oom16*1024/4));
lmk26=$(($oom26*1024/4));
lmk36=$(($oom36*1024/4));
lmk46=$(($oom46*1024/4));
lmk56=$(($oom56*1024/4));
lmk66=$(($oom66*1024/4));

#3072+
oom17=68
oom27=84
oom37=100
oom47=116
oom57=132
oom67=148

lmk17=$(($oom17*1024/4));
lmk27=$(($oom27*1024/4));
lmk37=$(($oom37*1024/4));
lmk47=$(($oom47*1024/4));
lmk57=$(($oom57*1024/4));
lmk67=$(($oom67*1024/4));

if [ "$mem" -lt 524288 ]; then
	busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree
	busybox echo "$lmk11,$lmk21,$lmk31,$lmk41,$lmk51,$lmk61" > /sys/module/lowmemorykiller/parameters/minfree
busybox echo "" >> $LS
busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ) RAM manager for 512mb devices successfully applied.." | busybox tee -a $LS
elif [ "$mem" -lt 786432 ]; then
	busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree
	busybox echo "$lmk12,$lmk22,$lmk32,$lmk42,$lmk52,$lmk62" >/sys/module/lowmemorykiller/parameters/minfree
busybox echo "" >> $LS
busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ) RAM manager for 768mb devices successfully applied.." | busybox tee -a $LS
elif [ "$mem" -lt 1048576 ]; then
	busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree
	busybox echo "$lmk13,$lmk23,$lmk33,$lmk43,$lmk53,$lmk63" > /sys/module/lowmemorykiller/parameters/minfree
busybox echo "" >> $LS
busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ) RAM manager for 1gb devices successfully applied.." | busybox tee -a $LS
elif [ "$mem" -lt 1572864 ]; then
	busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree
	busybox echo "$lmk14,$lmk24,$lmk34,$lmk44,$lmk54,$lmk64" > /sys/module/lowmemorykiller/parameters/minfree
busybox echo "" >> $LS
busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ) RAM manager for 1.5gb devices successfully applied.." | busybox tee -a $LS
elif [ "$mem" -lt 2097152 ]; then
	busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree
	busybox echo "$lmk15,$lmk25,$lmk35,$lmk45,$lmk55,$lmk65" > /sys/module/lowmemorykiller/parameters/minfree
busybox echo "" >> $LS
busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ) RAM manager for 2gb devices successfully applied.." | busybox tee -a $LS
elif [ "$mem" -lt 3145728 ]; then
	busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree
	busybox echo "$lmk16,$lmk26,$lmk36,$lmk46,$lmk56,$lmk66" > /sys/module/lowmemorykiller/parameters/minfree
busybox echo "" >> $LS
busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ) RAM manager for 3gb devices successfully applied.." | busybox tee -a $LS
else 
	busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree
	busybox echo "$lmk17,$lmk27,$lmk37,$lmk47,$lmk57,$lmk67" > /sys/module/lowmemorykiller/parameters/minfree
busybox echo "" >> $LS
busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ) RAM manager for 3gb+ devices successfully applied.." | busybox tee -a $LS
fi
